### ISSUE TITLE
Create function to format metadata and timeseries data for COMCAT and CWB

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/strongmotion-database#15]
_From @hschovanec-usgs on May 29, 2018 19:50_

- [ ] Format metadata as QuakeML or JSON
- [ ] Use obspy to format timeseries to be used by #25 

_Copied from original issue: usgs/shakemap-amp-tools#27_

**Comment by hschovanec-usgs** [comment]
closed by #8
